#!/bin/bash

# Run autopep8 to check if formatting is ok
# (stdout suppressed, because it prints the whole diff)
echo "Checking python formatting..."
autopep8 --diff -r blelog/ BLELog.py config.py plot.py char_decoders.py --global-config setup.cfg --exit-code > /dev/null

if [ $? -eq 0 ]
then
    echo "autopep8: Python formatting OK!"
    exit 0
else
    echo "autopep8: Error! Pyhon not formatted. Run hooks/format_all.sh!"  
    exit 1
fi


